<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Application GUI</title>
    <link rel="stylesheet" href="/assets/css/gui.css">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=<?= $data['apiKey'] ?>&sensor=false&libraries=places"></script>
    <script type="text/javascript" src="/assets/js/gui.js"></script>
</head>
<body>
    <div>
        <div id="map-container">
            <div id="map"></div>
        </div>
        <div id="buttons">
            <button id="btn-neptun-fountain">Find bars nearby Neptun Fountain</button>
            <button id="btn-my-position">Find bars near me</button>
        </div>
        <div id="error"></div>
    </div>
</body>
</html>
